Skip all the tests in the resize osd feature until the related BZs are fixed
red-hat-storage/ocs-ci pull request #10051
Opened 2024-07-07 11:40 UTC by yitzhak12

As per the discussion here: https://app.slack.com/client/E27SFGS2W/C06DWD30QTZ, we decided to remove this feature from 4.16.
We need to skip all the tests in the resize osd feature until the related BZs are fixed and the feature is ready.
In the PR we skip the BZs:

- https://bugzilla.redhat.com/show_bug.cgi?id=2279843
- https://bugzilla.redhat.com/show_bug.cgi?id=2295778

2024-07-07 13:06 UTC, yitzhak12 commented
The resize osd tests were skipped as expected.

2024-07-07 13:14 UTC, ebenahar approved these changes

2024-07-07 14:30 UTC, OdedViner submitted a review, later dismissed

2024-07-08 06:25 UTC, nehaberry requested changes
Please also add this major bug in the list of bugzillas

https://bugzilla.redhat.com/show_bug.cgi?id=2295750

Slack thread https://ibm-systems-storage.slack.com/archives/C06DWD30QTZ/p1720078827073439

2024-07-08 10:19 UTC, nehaberry approved these changes
LGTM

2024-07-08 14:09 UTC, prsurve approved these changes

2024-07-08 14:15 UTC, merged