Add additional condition check to ensure observability is successfully enabled
red-hat-storage/ocs-ci pull request #10718
Opened 2024-10-22 17:12 UTC by am-agrawa

fixes #10404

2024-10-22 17:36 UTC, prsurve requested changes

2024-10-22 17:36 UTC, prsurve commented on ocs_ci/deployment/deployment.py
> +                "oc get MultiClusterObservability observability -o jsonpath='{.status.conditions.status}'"
oc get MultiClusterObservability observability -o jsonpath='{.status.conditions[0].status}'

2024-10-22 18:18 UTC, am-agrawa commented on ocs_ci/deployment/deployment.py
> +                "oc get MultiClusterObservability observability -o jsonpath='{.status.conditions.status}'"
updated

2024-10-23 06:06 UTC, keemano approved these changes

2024-10-24 08:14 UTC, prsurve approved these changes

2024-11-07 17:22 UTC, am-agrawa commented
Deployment passed, observability successfully enabled- https://url.corp.redhat.com/3c20175

2024-11-13 07:10 UTC, keesturam approved these changes

2024-11-13 07:11 UTC, merged