update scale tests with fetched noobaa sc to avoid create reference to non-existing sc
red-hat-storage/ocs-ci pull request #10717
Opened 2024-10-22 15:48 UTC by DanielOsypenko

avoid failure when 50 OBCs created with sc reference "openshift-storage.noobaa.io" and become "lost" on Clusters with storage namespace different than "openshift-storage"

2024-11-11 19:40 UTC, DanielOsypenko commented
verification job - https://url.corp.redhat.com/b43b024
tests/cross_functional/scale/noobaa/test_scale_obc_create_delete.py::TestScaleOCBCreateDelete::test_scale_obc_create_delete_time
Failure is not related to changes
```
2024-11-11 20:40:51                      log.info("Waited for more than 10 mins but still no data")
2024-11-11 20:40:51  >                   raise UnexpectedBehaviour(
2024-11-11 20:40:51                          f"There is no obc deletion data in noobaa-operator logs for {no_data}"
2024-11-11 20:40:51                      )
2024-11-11 20:40:51  E                   ocs_ci.ocs.exceptions.UnexpectedBehaviour: There is no obc deletion data in noobaa-operator logs for ['obc-test-76c0d58b7d5b4e9781d8b7d53c4b6c8', 'obc-test-7cc3756c0f014c49b98e389d6f2f2d3', 'obc-test-a44b20e32b314eba92353ed2d3a70a8', 'obc-test-4b6ab1e09db14325aaa9adf7e49d568', 'obc-test-8231d23a4c2e43ec89abc027ceea711', 'obc-test-3bf162a6b7c44349ad3e12eca29ba9e', 'obc-test-9c906dfc85bc4337929415e20559c7c', 'obc-test-962333ba02f24e8497030fb8089032c']
```

2024-11-13 09:46 UTC, sagihirshfeld submitted a review, later dismissed

2024-11-22 05:38 UTC, ramkiperiy submitted a review, later dismissed

2024-12-04 08:23 UTC, dahorak requested changes

2024-12-04 08:23 UTC, dahorak commented on ocs_ci/ocs/scale_noobaa_lib.py
> +def fetch_noobaa_storage_class_name():
Please add docstring here.

2024-12-04 13:51 UTC, dahorak approved these changes

2024-12-04 13:55 UTC, sagihirshfeld approved these changes

2024-12-09 13:09 UTC, dahorak approved these changes

2024-12-09 13:17 UTC, ramkiperiy approved these changes

2024-12-09 13:18 UTC, merged

2024-12-09 14:31 UTC, DanielOsypenko commented
/cherry-pick release-4.17