Updated local storage template to accept different version
red-hat-storage/ocs-ci pull request #10886
Opened 2024-11-19 04:55 UTC by amr1ta

2024-11-26 11:36 UTC, fbalak approved these changes

2024-11-26 14:09 UTC, dahorak approved these changes

2025-02-07 07:14 UTC, dahorak approved these changes

2025-02-07 07:21 UTC, dahorak requested changes

2025-02-07 07:21 UTC, dahorak commented on ocs_ci/deployment/helpers/lso_helpers.py
> +                if not config.DEPLOYMENT.get("optional_operators_image"):
This "negative" condition will never be met - since the whole block is in `if config.DEPLOYMENT.get("optional_operators_image"):` condition.

2025-02-07 07:21 UTC, dahorak commented on ocs_ci/deployment/helpers/lso_helpers.py
> +                    _dict["spec"]["image"] = ocp_ga_version
`ocp_ga_version` variable will probably contain just version string, not full image url

2025-05-21 05:07 UTC, amr1ta commented on ocs_ci/deployment/helpers/lso_helpers.py
> +                if not config.DEPLOYMENT.get("optional_operators_image"):
Have addressed this in latest commit

2025-05-21 05:09 UTC, amr1ta commented on ocs_ci/deployment/helpers/lso_helpers.py
> +                    _dict["spec"]["image"] = ocp_ga_version
yes it is value like 4.19. which is used in option-operator catalogsource creation for the image details.
like,
`image: quay.io/openshift-qe-optional-operators/aosqe-index:v4.19`

2025-05-21 05:20 UTC, suchita-g approved these changes

2025-05-21 05:33 UTC, DanielOsypenko approved these changes

2025-05-21 05:36 UTC, dahorak approved these changes

2025-05-21 05:41 UTC, merged