Fix-2758
red-hat-storage/ocs-ci pull request #2759
Opened 2020-08-19 07:41 UTC by ramkiperiy

Fixed issues 2758, changed fixture to be at class level.
Commented ceph and resource checks which is increasing the scale execution time

Signed-off-by: Ramakrishnan <rperiyas@redhat.com>

2020-08-19 07:41 UTC, ramkiperiy commented
Fixes issue https://github.com/red-hat-storage/ocs-ci/issues/2758

2020-08-19 17:31 UTC, ramkiperiy commented
Testing it locally, can't execute this tests in jenkins due to memory allocation problem.

2020-09-07 04:39 UTC, keesturam requested changes

2020-09-07 04:39 UTC, keesturam commented on tests/e2e/scale/test_ceph_pod_respin_in_scaled_cluster.py
> +        scale_count=350, pods_per_iter=10, io_runtime=36000,
@ramkiperiy We used to run IO on 1500 pods for 10 hours earlier and now we run,
IOs on 350 pods for 10 hours, followed by the creation of 350 pods without IOs and then 400 pods with ~1 hour and 400 pods without IO. 

We'll simply use 400 pods for each iteration and run IOs for 18000 seconds alternatively. IMO, It is okay to cross 1500 pods. (we anyway don't run IOs on all of them)

Also, is there any reason we run IO for such a long time?

2020-10-09 05:48 UTC, ramkiperiy commented
Planning to implement kube jobs to scale pvc+pod, so it then holding on merging this PR.
Will create new PR for changing the fixture scope to "Class"

2020-11-20 09:08 UTC, ramkiperiy commented
Closing this PR since entire script needs re-work to use kube_job or other python method which doesn't use more Object creations.

2020-11-20 09:08 UTC, closed without merging