Tests to verify PVC snapshot restore with access mode different than parent PVC
red-hat-storage/ocs-ci pull request #3289
Opened 2020-11-09 11:38 UTC by jilju

Test to verify PVC snapshot restore with access mode different than parent PVC
OCS-2410 - FT-Restore snapshot with access mode different than that of parent PVC

Signed-off-by: Jilju Joy <jijoy@redhat.com>

2020-11-15 11:27 UTC, ebenahar approved these changes

2020-11-17 22:14 UTC, clacroix12 requested changes
This PR was raised before black was integrated with travis-ci. Please rebase on master and ensure black formatting is done.

2020-11-18 04:46 UTC, jilju commented
> This PR was raised before black was integrated with travis-ci. Please rebase on master and ensure black formatting is done.

@clacroix12  Rebased and applied black format.

2020-11-18 18:50 UTC, clacroix12 approved these changes
LGTM

2020-11-19 08:50 UTC, ebenahar approved these changes

2020-11-19 08:50 UTC, merged