pqsql: Fixed timeout issue and enable Azure support for scale
red-hat-storage/ocs-ci pull request #3631
Opened 2021-01-06 21:19 UTC by tiffanyn108

Fixed https://github.com/red-hat-storage/ocs-ci/issues/3455
Enable Azure support.

Signed-off-by: Tiffany Nguyen <tunguyen@redhat.com>

2021-01-07 01:29 UTC, tiffanyn108 commented
For some reason, Jenkins report is not correct.
Test case is passed as shown in the log: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/16079/testReport/

2021-01-08 05:21 UTC, keesturam commented on ocs_ci/ocs/scale_pgsql.py
> +        config.ENV_DATA["platform"].lower() == "vsphere" or "baremetal" or "azure"
azure is 'ipi'

2021-01-13 19:40 UTC, tiffanyn108 commented on ocs_ci/ocs/scale_pgsql.py
> +        instance_type = instance_type if instance_type else "m5.4xlarge"
I will look into this change for Azure.

2021-07-07 04:29 UTC, ramkiperiy commented on ocs_ci/ocs/scale_pgsql.py
> +        instance_type = instance_type if instance_type else "m5.4xlarge"
@tiffanyn108 please re-work on this PR #4467 (RHV) #4150 (Azure), we have now support for scaling nodes in Azure and RHV using custom machineset.

2021-08-06 07:36 UTC, ramkiperiy requested changes
This PR needs rebase with Azure and RHV support PR's merged recently.

2021-08-23 17:56 UTC, tiffanyn108 commented
Closing this PR.  Will need to revisit later.

2021-08-23 17:56 UTC, closed without merging