Fixes: #4068
red-hat-storage/ocs-ci pull request #4071
Opened 2021-03-29 15:29 UTC by petr-balogh

Fixes: #4056

Signed-off-by: Petr Balogh <pbalogh@redhat.com>

2021-03-29 15:33 UTC, petr-balogh commented
Verification triggered here:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/view/Upgrade-OCS/job/qe-trigger-vsphere-upi-1az-rhcos-vsan-3m-3w-upgrade-ocs-auto/32/console

2021-03-30 13:01 UTC, dahorak requested changes

2021-03-30 13:01 UTC, dahorak commented on ocs_ci/ocs/ocs_upgrade.py
> +            count=noobaa_pods + max_endpoints,
Same here with `max_endpoints`.

2021-03-30 13:23 UTC, ebenahar commented on ocs_ci/ocs/ocs_upgrade.py
> +            count=noobaa_pods + min_endpoints,
@dahorak `min_endpoints` and `max_endpoints` exist in the nooaa CR starting OCS 4.6

2021-03-30 13:30 UTC, petr-balogh commented on ocs_ci/ocs/ocs_upgrade.py
> +            count=noobaa_pods + max_endpoints,
Good catch Daniel, I  sent a fix.

2021-03-30 13:31 UTC, dahorak commented on ocs_ci/ocs/ocs_upgrade.py
> +            count=noobaa_pods + min_endpoints,
My concern was about python variables not defined under the condition mentioned above - fixed in the recent update.

2021-03-30 13:31 UTC, dahorak submitted a review, later dismissed

2021-03-30 13:40 UTC, petr-balogh commented
New verification triggered here: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/view/Upgrade-OCS/job/qe-trigger-aws-ipi-3az-rhcos-3m-3w-upgrade-ocs-auto/10/console

2021-03-30 13:42 UTC, petr-balogh commented on ocs_ci/ocs/ocs_upgrade.py
> +    noobaa_pods = 2 if upgrade_version < parse_version("4.3") else 3
Missed this comment. I am running verification now how it is..  Next time I will touch this part I can change.

2021-03-30 14:26 UTC, jimdevops19 approved these changes

2021-03-30 16:42 UTC, ebenahar submitted a review, later dismissed

2021-03-31 12:39 UTC, dahorak approved these changes

2021-03-31 12:40 UTC, petr-balogh commented on ocs_ci/ocs/ocs_upgrade.py
> +    noobaa_pods = 2 if upgrade_version < parse_version("4.3") else 3
Finally I removed this as part of this PR when I did last changes

2021-03-31 12:45 UTC, merged