Adding fixture for cleanup function.
red-hat-storage/ocs-ci pull request #4269
Opened 2021-05-07 05:12 UTC by tiffanyn108

Use fixture for cleanup function.
Fixed https://github.com/red-hat-storage/ocs-ci/issues/4161

2021-05-07 06:40 UTC, keesturam approved these changes
Nice, LGTM.

2021-05-07 07:02 UTC, fbalak requested changes
Please use the fixture also in tests `test_scale_mcg_obc_creation` and `test_scale_rgw_obc_creation` in this file.

The fixture also needs to be listed among test parameters (e.g. https://github.com/red-hat-storage/ocs-ci/blob/eb07ae1402b7c1b0b7c58f9ed2d9063b069077b4/tests/ecosystem/upgrade/test_upgrade.py#L33) in order to be used. You can also set `autouse=True` in fixture marker parameter to make it used by all tests in the file without listing it in test parameters (e.g. https://github.com/red-hat-storage/ocs-ci/blob/6ecc96ca640e96448a16e2271f5553a7a6248c12/tests/e2e/registry/test_registry_reboot_node.py#L33).

2021-05-10 07:03 UTC, fbalak approved these changes

2021-05-12 04:04 UTC, keesturam approved these changes

2021-05-12 04:04 UTC, merged