Multi snapshot TC refactoring
red-hat-storage/ocs-ci pull request #5112
Opened 2021-11-18 09:44 UTC by Avilir

This PR is a re-factoring of the Multi-Snapshots TC to use only one script and not 2 scripts,
and adding a verification of the teardown process to make sure all data was deleted.

2021-11-21 20:44 UTC, ypersky1980 approved these changes

2021-11-21 20:44 UTC, ypersky1980 commented on tests/e2e/performance/csi_tests/test_pvc_multi_snapshot_performance.py
>      The test is trying to to take the maximum number of snapshot for one PVC
small spelling fix - maximal , not maximum

2021-11-21 20:44 UTC, ypersky1980 commented on tests/e2e/performance/csi_tests/test_pvc_multi_snapshot_performance.py
> +            log.error(f"Can not get the list of snapshot : {err}")
spelling fix: "Cannot get the list of snapshots"

2021-11-21 20:44 UTC, ypersky1980 commented on tests/e2e/performance/csi_tests/test_pvc_multi_snapshot_performance.py
> +            foreach snapshot : write data on the pod and take snapshot
for each - pleae add space

2021-11-21 20:44 UTC, ypersky1980 commented
Left some minor comments.

2021-11-22 07:50 UTC, ypersky1980 approved these changes

2021-11-23 09:34 UTC, pintojoy commented on ocs_ci/ocs/perftests.py
> +        # Quarry the storage usage every 2 Min. if no difference between two
spelling fix: Query the storage ...

2021-11-29 00:04 UTC, ypersky1980 approved these changes
LGTM

2021-12-17 11:04 UTC, keemano requested changes
`single comment`

2021-12-29 15:00 UTC, Avilir commented
Closing since new PR to fix issues in this one are WIP

2021-12-29 15:00 UTC, closed without merging