Retry mcg status check
red-hat-storage/ocs-ci pull request #5132
Opened 2021-11-24 11:39 UTC by jilju

External mode deployment failed with the error :
```
E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage get backingstore noobaa-default-backing-store -n openshift-storage -o yaml.
E           Error is Error from server (NotFound): backingstores.noobaa.io "noobaa-default-backing-store" not found

ocs_ci/utility/utils.py:511: CommandFailed
```
Signed-off-by: Jilju Joy <jijoy@redhat.com>

2021-11-24 11:44 UTC, petr-balogh commented
Triggered prod job here: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-vsphere-upi-1az-rhcos-external-3m-3w-tier4a/4/console for verification

2021-11-24 11:48 UTC, petr-balogh approved these changes

2021-11-24 14:02 UTC, vavuthu approved these changes

2021-11-30 15:00 UTC, ebenahar approved these changes

2021-11-30 15:27 UTC, MeridianExplorer requested changes
~~From what I gather, the change is mostly meant as a means to catch the retries when they fail due to `CommandFailed` exceptions;
In this case, I believe it'd be better to handle these exceptions in the retry functions, too.~~

~~I'd probably modify `noobaa_health_check()` to have a try-except that raises `NoobaaHealthException` if the status check failed.~~

I thought about it, and I think that this PR should work fine for most cases.

2021-11-30 16:16 UTC, MeridianExplorer approved these changes

2021-12-02 03:09 UTC, merged