[Close loop BZ: 1980299]: Delete default S3 bucket
red-hat-storage/ocs-ci pull request #5199
Opened 2021-12-07 12:25 UTC by parikshithb

Signed-off-by: Parikshith Byregowda <pbyregow@redhat.com>

2021-12-15 12:34 UTC, Akarsha-rai approved these changes

2021-12-16 06:52 UTC, PrasadDesala approved these changes

2021-12-16 11:41 UTC, MeridianExplorer requested changes
I'm afraid that this PR is not sufficient to close the loop, @parikshithb - I have sent you a private message that elaborates more

Edit:
I discussed this with Parikshith, the PR seems good 👍🏻

2021-12-16 11:52 UTC, MeridianExplorer approved these changes

2021-12-20 14:56 UTC, vavuthu approved these changes

2021-12-20 14:56 UTC, merged