FIO | push performance results into the dashboard
red-hat-storage/ocs-ci pull request #5276
Opened 2021-12-23 13:25 UTC by Avilir

Signed-off-by: Avi Layani <alayani@redhat.com>

2021-12-23 14:54 UTC, Avilir commented
until #5277 will fix, i am running the validation locally.

2021-12-26 18:14 UTC, ypersky1980 requested changes
@Avilir  , Can you use class ResultsAnalyse from ocs_ci.ocs.perfresult  in this test as well, instead of FIOResultsAnalyse ( not needed after you use ResultsAnalyse from ocs_ci.ocs.perfresult) ?

2021-12-27 09:15 UTC, Avilir commented
> @Avilir , Can you use class ResultsAnalyse from ocs_ci.ocs.perfresult in this test as well, instead of FIOResultsAnalyse ( not needed after you use ResultsAnalyse from ocs_ci.ocs.perfresult) ?

since this object have more methods, which is not part of `ResultsAnalyse` and not needed in other objects, i created a new object.

2021-12-27 09:27 UTC, ypersky1980 approved these changes

2021-12-29 11:51 UTC, keemano commented on tests/e2e/performance/io_workload/test_fio_benchmark.py
> +        log.info(f"reslut path is : {self.results_path}")
spelling fix:- "result"

2021-12-29 11:53 UTC, Avilir commented
from the PR validation job : 
```
2021-12-29 10:57:33  08:57:33 - MainThread - ocs_ci.utility.perf_dash.dashboard_api - INFO - Test results pushed to the DB!
2021-12-29 10:57:33  08:57:33 - MainThread - ocs_ci.ocs.perftests - INFO - Full results report can be found at : http://10.0.78.167:8080/index.php?version1=14&build1=24&platform1=8&az_topology1=3&test_name%5B%5D=1&submit=Choose+options
2021-12-29 10:57:33  08:57:33 - MainThread - ocs_ci.utility.perf_dash.dashboard_api - INFO - Closing the DB connection
2021-12-29 10:57:33  PASSED                                                                   [100%]
```
and all results are in the performance dashboard

2021-12-29 14:40 UTC, ebenahar approved these changes

2021-12-29 14:58 UTC, merged