adding csi times and renaming the test
red-hat-storage/ocs-ci pull request #5987
Opened 2022-06-04 21:19 UTC by ypersky1980

This PR contains the following enhancements: 

1) Renaming the test so that similarly to bulk pod attach and pod reattach test this test will be called "pod attach" and not "pvc attach" test

2) Adding CSI measurements for pod attach action and reporting those measurements to the ES. 

Signed-off-by: Yulia Persky <ypersky@redhat.com>

2022-06-06 15:14 UTC, Avilir submitted a review, later dismissed

2022-06-06 20:32 UTC, ypersky1980 commented on ocs_ci/helpers/performance_lib.py
> +        raise Exception("Can not get volume handle")
Added here and in similar places.

2022-06-06 21:25 UTC, ypersky1980 commented
Please note the measurements taken by the test: 

22:12:33 - MainThread - test_pod_attachtime - INFO  - Interface: CephBlockPool, PVC size: 5 GB. pod number 1 start time: 6 seconds, csi start time is 0.31539900000000004
22:12:33 - MainThread - test_pod_attachtime - INFO  - Interface: CephBlockPool, PVC size: 5 GB. pod number 2 start time: 9 seconds, csi start time is 0.185779
22:12:33 - MainThread - test_pod_attachtime - INFO  - Interface: CephBlockPool, PVC size: 5 GB. pod number 3 start time: 8 seconds, csi start time is 0.158137
22:12:33 - MainThread - test_pod_attachtime - INFO  - Interface: CephBlockPool, PVC size: 5 GB. pod number 4 start time: 9 seconds, csi start time is 0.175396
22:12:33 - MainThread - test_pod_attachtime - INFO  - Interface: CephBlockPool, PVC size: 5 GB. pod number 5 start time: 8 seconds, csi start time is 0.158057
22:12:33 - MainThread - test_pod_attachtime - INFO  - Interface: CephBlockPool, PVC size: 5 GB. The standard deviation percent for csi start time of the sampled 5 pods is 33.432320075105174

22:12:33 - MainThread - test_pod_attachtime - INFO  - Interface: CephBlockPool, PVC size: 5 GB. The average time for the sampled 5 pods is 8 seconds.
22:12:33 - MainThread - test_pod_attachtime - INFO  - Interface: CephBlockPool, PVC size: 5 GB. The average csi time for the sampled 5 pods is 0.1985536 seconds.

====================================================================


22:20:21 - MainThread - test_pod_attachtime - INFO  - Interface: CephFileSystem, PVC size: 5 GB. pod number 1 start time: 4 seconds, csi start time is 0.126086
22:20:21 - MainThread - test_pod_attachtime - INFO  - Interface: CephFileSystem, PVC size: 5 GB. pod number 2 start time: 9 seconds, csi start time is 0.07191399999999999
22:20:21 - MainThread - test_pod_attachtime - INFO  - Interface: CephFileSystem, PVC size: 5 GB. pod number 3 start time: 8 seconds, csi start time is 0.052207
22:20:21 - MainThread - test_pod_attachtime - INFO  - Interface: CephFileSystem, PVC size: 5 GB. pod number 4 start time: 8 seconds, csi start time is 0.043347000000000004
22:20:21 - MainThread - test_pod_attachtime - INFO  - Interface: CephFileSystem, PVC size: 5 GB. pod number 5 start time: 8 seconds, csi start time is 0.044846000000000004
22:20:21 - MainThread - test_pod_attachtime - INFO  - Interface: CephFileSystem, PVC size: 5 GB. The standard deviation percent for csi start time of the sampled 5 pods is 51.08794404778807


22:20:21 - MainThread - test_pod_attachtime - INFO  - Interface: CephFileSystem, PVC size: 5 GB. The average time for the sampled 5 pods is 7.4 seconds.
22:20:21 - MainThread - test_pod_attachtime - INFO  - Interface: CephFileSystem, PVC size: 5 GB. The average csi time for the sampled 5 pods is 0.06768 seconds.

2022-06-07 02:52 UTC, yati1998 requested changes

2022-06-07 02:52 UTC, yati1998 commented on ocs_ci/helpers/performance_lib.py
> +def pod_csi_time(interface, pv_name, start_time, namespace=constants.OPENSHIFT_STORAGE_NAMESPACE):
I would prefer pod_attach_csi_time than pod_csi_time.

2022-06-07 02:52 UTC, yati1998 commented on ocs_ci/helpers/performance_lib.py
> +    Get the starting/ending creation time of a PVC based on provisioner logs
The comments still says that the function calculates the creation time of PVC? Can you check this again?

2022-06-07 05:56 UTC, Avilir submitted a review, later dismissed
LGTM

2022-06-07 08:08 UTC, yati1998 approved these changes

2022-06-07 10:52 UTC, ramkiperiy approved these changes

2022-06-07 11:06 UTC, Avilir approved these changes
LGTM

2022-06-07 11:10 UTC, pintojoy approved these changes
LGTM

2022-06-07 11:17 UTC, merged