Fix 6544
red-hat-storage/ocs-ci pull request #6545
Opened 2022-10-06 17:37 UTC by jilju

Verify pod node name is present before selecting node.
Fixes #6544
Signed-off-by: Jilju Joy <jijoy@redhat.com>

2022-10-06 17:55 UTC, jilju commented
Verified https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/17238/testReport/

2022-10-14 05:43 UTC, suchita-g commented on ocs_ci/ocs/resources/pod.py
> +    assert node_name, f"Node name not found for the pod {pod_obj.name}"
+1

2022-10-18 09:24 UTC, jilju commented on ocs_ci/ocs/resources/pod.py
> +    assert node_name, f"Node name not found for the pod {pod_obj.name}"
Done.

2022-10-18 09:28 UTC, fbalak requested changes

2022-10-18 09:28 UTC, fbalak commented on ocs_ci/ocs/resources/pod.py
> -    return node.get_node_objs(node_names=node_name)[0]
return statement was deleted. Now the function doesn't return the value.

2022-10-18 12:10 UTC, fbalak approved these changes

2022-10-20 06:42 UTC, suchita-g approved these changes

2022-10-20 06:48 UTC, merged