BZ-2142763 Prometheus File
red-hat-storage/ocs-ci pull request #7146
Opened 2023-02-21 20:47 UTC by OdedViner

2023-02-22 15:27 UTC, fbalak requested changes
lgtm but the test should be in a different file

2023-02-22 15:27 UTC, fbalak commented on tests/manage/monitoring/prometheus/test_deployment_status.py
> +def test_prometheus_file():
This test should be in a different file. You can create a new one in the same directory. Something like `test_prometheus_rules.py`.

2023-02-22 15:27 UTC, fbalak commented on tests/manage/monitoring/prometheus/test_deployment_status.py
> +@bugzilla("2142763")
please add polarion id

2023-03-01 13:39 UTC, OdedViner commented on tests/manage/monitoring/prometheus/test_deployment_status.py
> +@bugzilla("2142763")
done

2023-03-01 13:41 UTC, fbalak approved these changes

2023-03-03 06:25 UTC, PrasadDesala approved these changes

2023-03-03 11:22 UTC, merged