Add retry and wait time to get pod object in test_drain_mcg_pod_node
red-hat-storage/ocs-ci pull request #7155
Opened 2023-02-22 23:47 UTC by tiffanyn108

Fixed issue [# 6963](https://github.com/red-hat-storage/ocs-ci/issues/6963)
Added retry loop and wait time to get god object.

2023-02-23 04:27 UTC, tiffanyn108 commented
> PR validation
> 
> Cluster Name: Cluster Configuration: PR Test Suite: tier3 PR Test Path: tests/manage/mcg/test_mcg_resources_disruptions.py Additional Test Params: OCP VERSION: 4.12 OCS VERSION: 4.12 tested against branch: master
> 
> [Job UNSTABLE](https://url.corp.redhat.com/a26067d) (some or all tests failed).

Failure due to issue https://bugzilla.redhat.com/show_bug.cgi?id=1903573 while running "test_db_scc" test.
"test_drain_mcg_pod_node" is passed as expected.

2023-03-10 00:18 UTC, tiffanyn108 commented
> tests/manage/mcg/test_mcg_resources_disruptions.py

The failure due to SCC (Security Context Constraint).  This is fixed in[ PR# 6811](https://github.com/red-hat-storage/ocs-ci/pull/6811))

2023-03-12 12:51 UTC, sagihirshfeld commented on tests/manage/mcg/test_mcg_resources_disruptions.py
> +        while True:
We should use utils.py::TimeoutSampler or retry.py::retry instead for brevity, better maintainability and readability

2023-03-12 12:56 UTC, sagihirshfeld requested changes
The original issue only happens after the draining of the node at line 179, so we should only be retrying while retrieving the pod_obj at line 185.

2023-10-11 20:04 UTC, closed without merging