Test_ceph_osd_low_ops_alert backport 4.10
red-hat-storage/ocs-ci pull request #8142
Opened 2023-07-31 12:12 UTC by DanielOsypenko

Cherry pick:
https://github.com/red-hat-storage/ocs-ci/pull/7897

2023-08-02 07:48 UTC, DanielOsypenko commented
> PR validation on existing cluster
> 
> Cluster Name: dosypenk-18-c Cluster Configuration: PR Test Suite: tier3 PR Test Path: tests/manage/monitoring/test_workload_with_distruptions.py::TestCephOSDSlowOps::test_ceph_osd_low_ops_alert Additional Test Params: OCP VERSION: 4.10 OCS VERSION: 4.10 tested against branch: release-4.10
> 
> [Job UNSTABLE](https://url.corp.redhat.com/3e8aef6) (some or all tests failed).

bz: https://bugzilla.redhat.com/show_bug.cgi?id=2228359

2023-08-16 11:47 UTC, fbalak requested changes
There seems to be some out of scope changes to constants file

2023-08-16 11:47 UTC, fbalak commented on ocs_ci/ocs/constants.py
> +NOOBAA_DB_SERVICE_ACCOUNT_NAME = "noobaa-db"
Why are these changes done as part of backport pr?

2023-09-27 08:47 UTC, DanielOsypenko commented
opened https://github.com/red-hat-storage/ocs-ci/pull/8587 instead

2023-09-27 08:47 UTC, closed without merging