Exclude checking the pod statuses with the name prefix "report-status-to-provider-"
red-hat-storage/ocs-ci pull request #8434
Opened 2023-09-07 15:32 UTC by yitzhak12

In the PR, I implemented the following:
- In the functions `check_pods_after_node_replacement` and `check_pods_in_running_state`, exclude checking the pod statuses with the name prefix `report-status-to-provider-`.
- Add the param `exclude_pod_name_prefixes` to the functions `check_pods_in_statuses` and `get_pods_in_statuses` for excluding the pod names with specific prefixes.

2023-09-13 10:47 UTC, yitzhak12 commented
I needed to increase the timeout of waiting for the machine to reach the Failed state, as sometimes it takes almost 10 minutes.

2023-09-13 10:51 UTC, yitzhak12 commented
The pr validation job also passed when running the test on an MS consumer cluster: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-odf-multicluster/1932/.

2023-09-14 08:10 UTC, ebondare approved these changes

2023-09-14 08:19 UTC, suchita-g approved these changes

2023-09-14 11:28 UTC, dahorak commented on ocs_ci/ocs/resources/pod.py
> +        exclude_pod_name_prefixes (list): The list of the pod name prefixes to exclude from the pods to get
This line and few other lines in the docs strings are longer than 120 characters (in the [Coding Guidelines](https://ocs-ci.readthedocs.io/en/latest/coding_guidelines.html) we have even 79 characters, but [in tox.ini](https://github.com/red-hat-storage/ocs-ci/blob/master/tox.ini#L42) there is 120). I'm little bit confused how it passed the tox though.

2023-09-14 11:28 UTC, dahorak requested changes
~~Some of the docstrings have too long lines.~~
I've wrongly check the lines length.

2023-09-14 11:56 UTC, dahorak approved these changes

2023-09-14 12:50 UTC, merged