increase alert cleared timeout for test_ceph_health
red-hat-storage/ocs-ci pull request #9505
Opened 2024-03-18 13:10 UTC by fbalak

Fixes https://github.com/red-hat-storage/ocs-ci/issues/8138

2024-03-19 12:47 UTC, ebenahar submitted a review, later dismissed

2024-03-27 07:54 UTC, fbalak commented
Verified: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/35465/
Check for clearing alerts passed correctly

2024-03-27 17:37 UTC, DanielOsypenko requested changes
I assume Cluster issues that we are checking are not covering potential bug

2024-03-27 17:37 UTC, DanielOsypenko commented on tests/functional/monitoring/prometheus/alerts/test_ceph.py
> +    health_wait = 420
this value is set to 420, but these are minutes. 420/60 = 7, total 7 hours of wait .

```
 api.check_alert_cleared(
        label=target_label,
        measure_end_time=stop_time,
        time_min=health_wait,
    )
```

2024-03-27 17:38 UTC, DanielOsypenko approved these changes

2024-03-27 17:40 UTC, DanielOsypenko commented on tests/functional/monitoring/prometheus/alerts/test_ceph.py
> +    health_wait = 420
sorry, ignore this.
time_min - it looks more like time in minutes than minimal time, which I expected to see as a min_time

As an enhancement, suggest to change this parameter name. Up to you, in this PR or in another.

2024-03-28 08:37 UTC, dahorak approved these changes

2024-03-28 09:07 UTC, merged